azure:
  free_disk_space: true
  store_build_artifacts: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_64: github_actions
  osx_64: gihub_acitons
  win_64: github_actions
test_on_native_only: true
skip_render:
  - README.md
  - LICENSE.txt
  - .github/workflows/automerge.yml
  - .github/workflows/webservices.yml
